# Generated by Django 5.0.6 on 2024-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_salary_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
