# Generated by Django 5.0.6 on 2024-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_last_salary_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_got',
            field=models.IntegerField(default=1),
        ),
    ]
