# Generated by Django 5.0.6 on 2024-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_salary_got'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='money_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
