# Generated by Django 5.0.6 on 2024-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_money_per_hour_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='money_per_hour_at_purchase',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
