# Generated by Django 5.0.6 on 2024-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_useritem_money_per_hour_at_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_collection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
